//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteFeshFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonHang
    {
        public DonHang()
        {
            this.CTDonHangs = new HashSet<CTDonHang>();
        }
    
        public string MaDonHang { get; set; }
        public string MaKH { get; set; }
        public string DiaChiNhan { get; set; }
        public string SDTNhan { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public Nullable<System.DateTime> NgayGiao { get; set; }
    
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
