//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteFeshFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaBan
    {
        public int MaGia { get; set; }
        public string MaSP { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<double> GiaBan1 { get; set; }
        public Nullable<System.DateTime> NgayApDung { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
