//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteFeshFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiamGia
    {
        public int MaGiamGia { get; set; }
        public string MaSP { get; set; }
        public Nullable<double> PhanTram { get; set; }
        public Nullable<double> GiaGiam { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    
        public virtual SanPham SanPham { get; set; }
    }
}
