//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteFeshFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonNhap
    {
        public HoaDonNhap()
        {
            this.CTHoaDonNhaps = new HashSet<CTHoaDonNhap>();
        }
    
        public string MaHoaDonNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public string MaNCC { get; set; }
        public Nullable<double> TongTien { get; set; }
    
        public virtual ICollection<CTHoaDonNhap> CTHoaDonNhaps { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
    }
}
