//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteFeshFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
            this.CTDonHangs = new HashSet<CTDonHang>();
            this.CTHoaDonNhaps = new HashSet<CTHoaDonNhap>();
            this.GiaBans = new HashSet<GiaBan>();
            this.GiamGias = new HashSet<GiamGia>();
        }
    
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string MaLoaiSP { get; set; }
        public string DonVi { get; set; }
        public string MoTa { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<double> DonGia { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
        public virtual ICollection<CTDonHang> CTDonHangs { get; set; }
        public virtual ICollection<CTHoaDonNhap> CTHoaDonNhaps { get; set; }
        public virtual ICollection<GiaBan> GiaBans { get; set; }
        public virtual ICollection<GiamGia> GiamGias { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
