//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebsiteFeshFood
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.BinhLuans = new HashSet<BinhLuan>();
        }
    
        public long UserID { get; set; }
        public string UserName { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
        public string SDT { get; set; }
        public string Role { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<BinhLuan> BinhLuans { get; set; }
    }
}
